
package eu.esens.espdvcd.builder;

import eu.esens.espdvcd.model.ESPDRequest;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import eu.esens.espdvcd.model.SelectableCriterion;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class BuilderESPDTest {
    
    InputStream is;
    public BuilderESPDTest() {
    }
    
    @Before
    public void setUp() {
        is = BuilderESPDTest.class.getResourceAsStream("/espd-request.xml");
        Assert.assertNotNull(is);
    }

    @Test
    public void createESPDRequestFromFile() throws Exception {
        
        ESPDBuilder espdBuiler = new ESPDBuilder();
        // Here we load an ESPD Request generated by the EU Service
        ESPDRequest espd = espdBuiler.createFromXML(is);
        Assert.assertNotNull(espd);

        // We create an XML from our simple model 
        String XML = espdBuiler.createXMLasString(espd);
        Assert.assertNotNull(XML);
        System.out.println(XML);
    }

    @Test
    public void deselectExclusionCriterion() throws Exception {

        ESPDBuilder espdBuiler = new ESPDBuilder();

        // Here we load an ESPD Request generated by the EU Service
        ESPDRequest originalEspd = espdBuiler.createFromXML(is);
        Assert.assertNotNull(originalEspd);

        // Deselect the first exclusion criterion
        originalEspd.getExclusionCriteriaList().get(0).setSelected(false);

        // Count the number of selected exclusion criteria and the total number of exclusion criteria in the original espd request
        int originalEspdExclusionCriteriaCount = originalEspd.getExclusionCriteriaList().size();
        int originalEspdExclusionCriteriaSelectedCount = 0;
        for (SelectableCriterion criterion : originalEspd.getExclusionCriteriaList()) {
            originalEspdExclusionCriteriaSelectedCount += (criterion.isSelected() ? 1 : 0);
        }

        // Export the ESPD Request to Xml string
        String exportedXml = espdBuiler.createXMLasString(originalEspd);

        // Reimport the ESPD Request from the Xml string
        InputStream stream = new ByteArrayInputStream(exportedXml.getBytes(StandardCharsets.UTF_8));
        ESPDRequest importedEspd = espdBuiler.createFromXML(stream);
        stream.close();
        Assert.assertNotNull(importedEspd);

        // Count the number of selected exclusion criteria and the total number of exclusion criteria in the imported espd request
        int importedEspdExclusionCriteriaCount = importedEspd.getExclusionCriteriaList().size();
        int importedEspdExclusionCriteriaSelectedCount = 0;
        for (SelectableCriterion criterion : importedEspd.getExclusionCriteriaList()) {
            importedEspdExclusionCriteriaSelectedCount += (criterion.isSelected() ? 1 : 0);
        }

        // Compare the number of selected exclusion criteria in espd and importedEspd
        Assert.assertEquals(originalEspdExclusionCriteriaCount, importedEspdExclusionCriteriaCount);
        Assert.assertNotEquals(originalEspdExclusionCriteriaSelectedCount, importedEspdExclusionCriteriaSelectedCount);
    }
}
