package eu.esens.espdvcd.retriever.criteria.resource.utils;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class TypeCodeUtils {

    private static List<String> regulatedV1TypeCodeList;
    private static Set<String> regulatedV1TypeCodeSet;

    public List<String> getV1RegulatedTypeCodeList() {

        if (regulatedV1TypeCodeList == null) {
            regulatedV1TypeCodeList = new ArrayList<>(createCriteriaTypeCodeSetRegulatedV1());
        }

        return regulatedV1TypeCodeList;
    }

    public static Set<String> getV1RegulatedTypeCodeSet() {

        if (regulatedV1TypeCodeSet == null) {
            regulatedV1TypeCodeSet = createCriteriaTypeCodeSetRegulatedV1();
        }

        return regulatedV1TypeCodeSet;
    }

    private static Set<String> createCriteriaTypeCodeSetRegulatedV2() {

        Set<String> set = new HashSet<>();

        // from taxonomy

        return set;
    }

    /**
     * Get a String with most recent v1.0.2 taxonomy Criteria typeCodes.
     *
     * @return Set with Criteria typeCodes
     */
    private static Set<String> createCriteriaTypeCodeSetRegulatedV1() {

        Set<String> set = new HashSet<>();

        // From taxonomy
        set.add("CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"); // 1
        set.add("CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"); // 2
        set.add("CRITERION.EXCLUSION.CONVICTIONS.FRAUD"); // 3
        set.add("CRITERION.EXCLUSION.CONVICTIONS.TERRORIST_OFFENCES"); // 4
        set.add("CRITERION.EXCLUSION.CONVICTIONS.MONEY_LAUNDERING"); // 5
        set.add("CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING"); // 6
        set.add("CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_TAXES"); // 7
        set.add("CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_SOCIAL_SECURITY"); // 8
        set.add("CRITERION.EXCLUSION.SOCIAL.ENVIRONMENTAL_LAW"); // 9
        set.add("CRITERION.EXCLUSION.SOCIAL.SOCIAL_LAW"); // 10
        set.add("CRITERION.EXCLUSION.SOCIAL.LABOUR_LAW"); // 11
        set.add("CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY"); // 12
        set.add("CRITERION.EXCLUSION.BUSINESS.INSOLVENCY"); // 13
        set.add("CRITERION.EXCLUSION.BUSINESS.CREDITORS_ARRANGEMENT"); // 14
        set.add("CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY_ANALOGOUS"); // 15
        set.add("CRITERION.EXCLUSION.BUSINESS.LIQUIDATOR_ADMINISTERED"); // 16
        set.add("CRITERION.EXCLUSION.BUSINESS.ACTIVITIES_SUSPENDED"); // 17
        set.add("CRITERION.EXCLUSION.MISCONDUCT.MC_PROFESSIONAL"); // 18
        set.add("CRITERION.EXCLUSION.MISCONDUCT.MARKET_DISTORTION"); // 19
        set.add("CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.PROCEDURE_PARTICIPATION"); // 20
        set.add("CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.PROCEDURE_PREPARATION"); // 21
        set.add("CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.EARLY_TERMINATION"); // 22
        set.add("CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.MISINTERPRETATION"); // 23
        set.add("CRITERION.EXCLUSION.NATIONAL.OTHER"); // 24
        set.add("CRITERION.SELECTION.SUITABILITY.PROFESSIONAL_REGISTER_ENROLMENT"); // 25
        set.add("CRITERION.SELECTION.SUITABILITY.TRADE_REGISTER_ENROLMENT"); // 26
        set.add("CRITERION.SELECTION.SUITABILITY.AUTHORISATION"); // 27
        set.add("CRITERION.SELECTION.SUITABILITY.MEMBERSHIP"); // 28
        set.add("CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.GENERAL_YEARLY"); // 29
        set.add("CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.AVERAGE_YEARLY"); // 30
        set.add("CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_YEARLY"); // 31
        set.add("CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_AVERAGE"); // 32
        set.add("CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SET_UP"); // 33
        set.add("CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.FINANCIAL_RATIO"); // 34
        set.add("CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.RISK_INDEMNITY_INSURANCE"); // 35
        set.add("CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.OTHER_REQUIREMENTS"); // 36
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.WORKS_PERFORMANCE"); // 37
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SUPPLIES_DELIVERY_PERFORMANCE"); // 38
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SERVICES_DELIVERY_PERFORMANCE"); // 39
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.TECHNICIANS_FOR_QUALITY_CONTROL"); // 40
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.TECHNICIANS_FOR_CARRYING_WORKS"); // 41
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.FACILITIES_FOR_QUALITY_ENSURING"); // 42
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.FACILITIES.FOR_STUDY_RESEARCH"); // 43
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.SUPPLY_CHAIN_MANAGEMENT"); // 44
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.CHECKS.ALLOWANCE_OF_CHECKS"); // 45
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.PROFESSIONAL.QUALIFICATIONS");  // 46
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.ENVIRONMENTAL_MANAGEMENT_MEASURES"); // 47
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.MANAGERIAL_STAFF"); // 48
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.AVERAGE_ANNUAL_MANPOWER"); // 49
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.EQUIPMENT"); // 50
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.SUBCONTRACTING_PROPORTION"); // 51
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.ARTEFACTS.NO_AUTHENTICATED_ARTEFACTS"); // 52
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.ARTEFACTS.AUTHENTICATED_ARTEFACTS"); // 53
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.CERTIFICATES.QUALITY_ASSURANCE.QA_INSTITUTES_CERTIFICATE"); // 54
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.CERTIFICATES.QUALITY_ASSURANCE.QA_INDEPENDENT_CERTIFICATE"); // 55
        set.add("CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.CERTIFICATES.ENVIRONMENTAL_MANAGEMENT.ENV_INDEPENDENT_CERTIFICATE"); // 56
        set.add("CRITERION.OTHER.EO_DATA.SHELTERED_WORKSHOP"); // 57
        set.add("CRITERION.OTHER.EO_DATA.REGISTERED_IN_OFFICIAL_LIST"); // 58
        set.add("CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS"); // 59
        set.add("CRITERION.OTHER.EO_DATA.RELIES_ON_OTHER_CAPACITIES"); // 60
        set.add("CRITERION.OTHER.EO_DATA.SUBCONTRACTS_WITH_THIRD_PARTIES"); // 61
        set.add("CRITERION.OTHER.EO_DATA.MEETS_THE_OBJECTIVE"); // 62
        // ALL_SATISFIED
        set.add("CRITERION.SELECTION.ALL_SATISFIED"); // 63

        return set;
    }

    public static void printDifferences(Set<String> set1, Set<String> set2) {

        set1.forEach(typeCode -> {

            if (!set2.contains(typeCode)) {
                System.out.println(typeCode);
            }

        });
    }

}
